// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_first_win = new UnifiedAchievement("first_win",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "first_victory"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIyKTG_KYOEAIQAQ"
#else
            "first_win"
#endif
            );

        public static UnifiedAchievement first_win
        {
            get { return s_first_win; }
        }

        private static readonly UnifiedAchievement s_semi_pro = new UnifiedAchievement("semi_pro",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "semi_pro"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIyKTG_KYOEAIQAg"
#else
            "semi_pro"
#endif
            );

        public static UnifiedAchievement semi_pro
        {
            get { return s_semi_pro; }
        }

        private static readonly UnifiedAchievement s_pro = new UnifiedAchievement("pro",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "pro"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIyKTG_KYOEAIQAw"
#else
            "pro"
#endif
            );

        public static UnifiedAchievement pro
        {
            get { return s_pro; }
        }

        private static readonly UnifiedAchievement s_veteran = new UnifiedAchievement("veteran",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "veteran"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIyKTG_KYOEAIQBA"
#else
            "veteran"
#endif
            );

        public static UnifiedAchievement veteran
        {
            get { return s_veteran; }
        }

        private static readonly UnifiedAchievement s_expert = new UnifiedAchievement("expert",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "expert"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIyKTG_KYOEAIQBQ"
#else
            "expert"
#endif
            );

        public static UnifiedAchievement expert
        {
            get { return s_expert; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_first_win,
            s_semi_pro,
            s_pro,
            s_veteran,
            s_expert,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "first_win", s_first_win },
            { "semi_pro", s_semi_pro },
            { "pro", s_pro },
            { "veteran", s_veteran },
            { "expert", s_expert }
        };
    }
}
